namespace TeslaSolarCharger.Shared.Enums;

public enum CarValueType
{
    ModuleTempMin,//0
    ModuleTempMax,//1
    BatteryHeaterOn,//2
    ChargeState,//3
    ChargeAmps,//4
    ChargeCurrentRequest,//5
    ChargePortLatch,//6
    DetailedChargeState,//7
    IsPluggedIn,//8
    IsCharging,//9
    ChargerPilotCurrent,//10
    Location,//11
    Longitude,//12
    Latitude,//13
    StateOfCharge,//14
    StateOfChargeLimit,//15
    ChargerPhases,//16
    ChargerVoltage,//17
    AsleepOrOffline,//18
    Gear,//19
    Speed,//20
    VehicleName,//21
    LocatedAtHome,//22
    LocatedAtWork,//23
    LocatedAtFavorite,//24
    DcChargingPower,//25
    FastChargerPresent,//26
    ChargingCableType,//27
    FastChargerType,//28
    IdealBatteryRange,//29
    RatedBatteryRange,//30
    EstimatedBatteryRange,//31
    NotEnoughPowerToHeat,//32
    InsideTemperature,//33
    OutsideTemperature,//34
    UsableStateOfCharge,//35
    BatteryVoltage,//36
    BatteryCurrent,//37
    Odometer,//38
    HvacFanStatus,//39
    HvacLeftTempRequest,//40
    HvacRightTempRequest,//41
    IsClimateOn,//42
    IsRearDefrosterOn,//43
    TpmsPressureFrontLeft,//44
    TpmsPressureFrontRight,//45
    TpmsPressureRearLeft,//46
    TpmsPressureRearRight,//47
    Unknown = 9999,
}
