// ReSharper disable InconsistentNaming
namespace TeslaSolarCharger.Shared.Enums;

public enum SpotPriceRegion
{
    AT,
    BE,
    BG,
    CH,
    CZ,
    DE_LU,
    DE_AT_LU,
    DK1,
    DK2,
    EE,
    ES,
    FI,
    FR,
    GR,
    HR,
    HU,
    IT_Calabria,
    IT_Centre_North,
    IT_Centre_South,
    IT_North,
    IT_SACOAC,
    IT_SACODC,
    IT_Sardinia,
    IT_Sicily,
    IT_South,
    LT,
    LV,
    ME,
    NL,
    NO1,
    NO2,
    NO2NSL,
    NO3,
    NO4,
    NO5,
    PL,
    PT,
    RO,
    RS,
    SE1,
    SE2,
    SE3,
    SE4,
    SI,
    SK,
}

public static class SpotPriceRegionExtensions
{
    public static string ToFriendlyName(this SpotPriceRegion region) => region switch
    {
        SpotPriceRegion.AT => "AT - Austria",
        SpotPriceRegion.BE => "BE - Belgium",
        SpotPriceRegion.BG => "BG - Bulgaria",
        SpotPriceRegion.CH => "CH - Switzerland",
        SpotPriceRegion.CZ => "CZ - Czech Republic",
        SpotPriceRegion.DE_LU => "DE-LU - Germany, Luxembourg",
        SpotPriceRegion.DE_AT_LU => "DE-AT-LU - Germany, Austria, Luxembourg",
        SpotPriceRegion.DK1 => "DK1 - Denmark 1",
        SpotPriceRegion.DK2 => "DK2 - Denmark 2",
        SpotPriceRegion.EE => "EE - Estonia",
        SpotPriceRegion.ES => "ES - Spain",
        SpotPriceRegion.FI => "FI - Finland",
        SpotPriceRegion.FR => "FR - France",
        SpotPriceRegion.GR => "GR - Greece",
        SpotPriceRegion.HR => "HR - Croatia",
        SpotPriceRegion.HU => "HU - Hungary",
        SpotPriceRegion.IT_Calabria => "IT-Calabria - Italy Calabria",
        SpotPriceRegion.IT_Centre_North => "IT-Centre-North - Italy Centre North",
        SpotPriceRegion.IT_Centre_South => "IT-Centre-South - Italy Centre South",
        SpotPriceRegion.IT_North => "IT-North - Italy North",
        SpotPriceRegion.IT_SACOAC => "IT-SACOAC - Italy Sardinia Corsica AC",
        SpotPriceRegion.IT_SACODC => "IT-SACODC - Italy Sardinia Corsica DC",
        SpotPriceRegion.IT_Sardinia => "IT-Sardinia - Italy Sardinia",
        SpotPriceRegion.IT_Sicily => "IT-Sicily - Italy Sicily",
        SpotPriceRegion.IT_South => "IT-South - Italy South",
        SpotPriceRegion.LT => "LT - Lithuania",
        SpotPriceRegion.LV => "LV - Latvia",
        SpotPriceRegion.ME => "ME - Montenegro",
        SpotPriceRegion.NL => "NL - Netherlands",
        SpotPriceRegion.NO1 => "NO1 - Norway 1",
        SpotPriceRegion.NO2 => "NO2 - Norway 2",
        SpotPriceRegion.NO2NSL => "NO2NSL - Norway North Sea Link",
        SpotPriceRegion.NO3 => "NO3 - Norway 3",
        SpotPriceRegion.NO4 => "NO4 - Norway 4",
        SpotPriceRegion.NO5 => "NO5 - Norway 5",
        SpotPriceRegion.PL => "PL - Poland",
        SpotPriceRegion.PT => "PT - Portugal",
        SpotPriceRegion.RO => "RO - Romania",
        SpotPriceRegion.RS => "RS - Serbia",
        SpotPriceRegion.SE1 => "SE1 - Sweden 1",
        SpotPriceRegion.SE2 => "SE2 - Sweden 2",
        SpotPriceRegion.SE3 => "SE3 - Sweden 3",
        SpotPriceRegion.SE4 => "SE4 - Sweden 4",
        SpotPriceRegion.SI => "SI - Slovenia",
        SpotPriceRegion.SK => "SK - Slovakia",
        _ => region.ToString(),
    };

    public static string ToRegionCode(this SpotPriceRegion region) => region switch
    {
        SpotPriceRegion.DE_LU => "DE-LU",
        SpotPriceRegion.DE_AT_LU => "DE-AT-LU",
        SpotPriceRegion.IT_Calabria => "IT-Calabria",
        SpotPriceRegion.IT_Centre_North => "IT-Centre-North",
        SpotPriceRegion.IT_Centre_South => "IT-Centre-South",
        SpotPriceRegion.IT_North => "IT-North",
        SpotPriceRegion.IT_SACOAC => "IT-SACOAC",
        SpotPriceRegion.IT_SACODC => "IT-SACODC",
        SpotPriceRegion.IT_Sardinia => "IT-Sardinia",
        SpotPriceRegion.IT_Sicily => "IT-Sicily",
        SpotPriceRegion.IT_South => "IT-South",
        _ => region.ToString().Replace("_", "-"),
    };
}
