using Microsoft.Extensions.DependencyInjection;
using TeslaSolarCharger.Shared.Helper;
using TeslaSolarCharger.Shared.Helper.Contracts;
using TeslaSolarCharger.Shared.Localization;
using TeslaSolarCharger.Shared.Localization.Contracts;
using TeslaSolarCharger.Shared.Localization.Registries;
using TeslaSolarCharger.Shared.Localization.Registries.Components;
using TeslaSolarCharger.Shared.Localization.Registries.Components.StartPage;
using TeslaSolarCharger.Shared.Localization.Registries.Pages;
using TeslaSolarCharger.Shared.Localization.Registries.PropertyRegistries;
using TeslaSolarCharger.Shared.Localization.Registries.PropertyRegistries.TemplateDtos;
using TeslaSolarCharger.Shared.Localization.Registries.Server;
using TeslaSolarCharger.Shared.Resources;
using TeslaSolarCharger.Shared.Resources.Contracts;

namespace TeslaSolarCharger.Shared;

public static class ServiceCollectionExtensions
{
    public static IServiceCollection AddSharedDependencies(this IServiceCollection services) =>
        services
            .AddTransient<IStringHelper, StringHelper>()
            .AddTransient<IConstants, Constants>()
            .AddTransient<IValidFromToHelper, ValidFromToHelper>()
            .AddSingleton<IPropertyLocalizationService, PropertyLocalizationService>()
            .AddSingleton<IPropertyLocalizationRegistry, BaseConfigurationBasePropertyLocalization>()
            .AddSingleton<IPropertyLocalizationRegistry, CarBasicConfigurationPropertyLocalization>()
            .AddSingleton<IPropertyLocalizationRegistry, ChargingStationConnectorPropertyLocalization>()
            .AddSingleton<IPropertyLocalizationRegistry, CarOverviewSettingsPropertyLocalization>()
            .AddSingleton<IPropertyLocalizationRegistry, CarChargingTargetPropertyLocalization>()
            .AddSingleton<IPropertyLocalizationRegistry, ModbusValueResultConfigurationPropertyLocalization>()
            .AddSingleton<IPropertyLocalizationRegistry, ValueConfigurationBasePropertyLocalization>()
            .AddSingleton<IPropertyLocalizationRegistry, JsonXmlResultConfigurationPropertyLocalization>()
            .AddSingleton<IPropertyLocalizationRegistry, ChargePricePropertyLocalization>()
            .AddSingleton<IPropertyLocalizationRegistry, DtoSmaEnergyMeterTemplateValueConfigurationPropertyLocalization>()
            .AddSingleton<IPropertyLocalizationRegistry, DtoModbusConfigurationBasePropertyLocalization>()
            .AddSingleton<IPropertyLocalizationRegistry, DtoSmaInverterTemplateValueConfigurationPropertyLocalization>()
            .AddSingleton<IPropertyLocalizationRegistry, DtoGenericModbusTemplateValueConfigurationPropertyLocalization>()
            .AddSingleton<IPropertyLocalizationRegistry, DtoGenericRestTemplateValueConfigurationPropertyLocalization>()
            .AddSingleton<IPropertyLocalizationRegistry, DtoSunSpecTemplateValueConfigurationPropertyLocalization>()
            .AddSingleton<IPropertyLocalizationRegistry, DtoFroniusSolarApiTemplateValueConfigurationPropertyLocalization>()
            .AddSingleton<IPropertyLocalizationRegistry, DtoSolaxTemplateValueConfigurationPropertyLocalization>()
            .AddSingleton<IPropertyLocalizationRegistry, DtoKostalModbusConfigurationPropertyLocalization>()
            .AddSingleton<IPropertyLocalizationRegistry, DtoTeslaPowerwallTemplateValueConfigurationPropertyLocalization>()
            .AddSingleton<IPropertyLocalizationRegistry, BackendLoginPropertyLocalization>()
            .AddSingleton<ITextLocalizationService, TextLocalizationService>()
            .AddSingleton<ITextLocalizationRegistry, SharedComponentLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, BaseConfigurationPageLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, SetupPageLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, CarSettingsPageLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, ChargeCostDetailPageLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, ChargeCostsListPageLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, CloudConnectionPageLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, ChargingStationsPageLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, HandledChargesListPageLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, HomePageLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, SupportPageLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, FixedPriceComponentLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, AutoReloadOnVersionChangeComponentLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, BackupComponentLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, ChargingStationConnectorsComponentLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, NavMenuComponentLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, CustomIconLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, CarDetailsComponentLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, CarSelectorComponentLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, CarControlCapabilityComponentLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, CarChargingSetupComponentLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, GenericValueConfigurationComponentLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, BackendInformationDisplayComponentLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, ChargeSummaryComponentLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, ChargingConnectorDetailsComponentLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, ChargingSchedulesChartComponentLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, ChargingSchedulesComponentLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, EditFormComponentLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, ChargingTargetConfigurationComponentLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, EnergyPredictionComponentLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, FleetApiTestComponentLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, BleConnectionTestComponentLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, HiddenErrorsComponentLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, LegendItemComponentLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, LoadpointComponentLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, LoggedErrorsComponentLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, ManualOcppChargingComponentLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, NotChargingAtExpectedPowerReasonsComponentLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, NotChargingWithExpectedPowerReasonLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, PowerBufferComponentLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, InstallationInformationLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, MerryChristmasAndHappyNewYearComponentLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, DialogsLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, TimeSeriesChartPageLocalizationRegistry>()
            .AddSingleton<ITextLocalizationRegistry, ValueSourceConfigurationLocalizationRegistry>()
        ;
}
