using System.Text.Json;
using Xunit;
using Xunit.Abstractions;

namespace TeslaSolarCharger.Tests.Services.Server;

public class OcppWebSocketConnectionHandlingService : TestBase
{
    public OcppWebSocketConnectionHandlingService(ITestOutputHelper outputHelper)
        : base(outputHelper)
    {
    }

    [Theory]
    [InlineData("[2,\"2025051820053400000095\",\"MeterValues\",{\"connectorId\":1,\"transactionId\":10,\"meterValue\":[{\"timestamp\":\"2025-05-18T20:07:49.000Z\",\"sampledValue\":[{\"value\":\"1402812\",\"unit\":\"Wh\",\"measurand\":\"Energy.Active.Import.Register\"},{\"value\":\"0.000000\",\"unit\":\"V\",\"measurand\":\"Voltage\",\"phase\":\"L1\"},{\"value\":\"0.000000\",\"unit\":\"V\",\"measurand\":\"Voltage\",\"phase\":\"L2\"},{\"value\":\"0.000000\",\"unit\":\"V\",\"measurand\":\"Voltage\",\"phase\":\"L3\"},{\"value\":\"0.009000\",\"unit\":\"A\",\"measurand\":\"Current.Export\",\"phase\":\"L1\"},{\"value\":\"0.009000\",\"unit\":\"A\",\"measurand\":\"Current.Import\",\"phase\":\"L1\"},{\"value\":\"0.008000\",\"unit\":\"A\",\"measurand\":\"Current.Export\",\"phase\":\"L2\"},{\"value\":\"0.008000\",\"unit\":\"A\",\"measurand\":\"Current.Import\",\"phase\":\"L2\"},{\"value\":\"0.009000\",\"unit\":\"A\",\"measurand\":\"Current.Export\",\"phase\":\"L3\"},{\"value\":\"0.009000\",\"unit\":\"A\",\"measurand\":\"Current.Import\",\"phase\":\"L3\"},{\"value\":\"0\",\"unit\":\"W\",\"measurand\":\"Power.Offered\"},{\"value\":\"0\",\"unit\":\"W\",\"measurand\":\"Power.Active.Import\"}]}]}]")]
    [InlineData("[2,\"2025051820053900000096\",\"MeterValues\",{\"connectorId\":1,\"transactionId\":10,\"meterValue\":[{\"timestamp\":\"2025-05-18T20:07:51.000Z\",\"sampledValue\":[{\"value\":\"1402812\",\"unit\":\"Wh\",\"measurand\":\"Energy.Active.Import.Register\"},{\"value\":\"0.000000\",\"unit\":\"V\",\"measurand\":\"Voltage\",\"phase\":\"L1\"},{\"value\":\"0.000000\",\"unit\":\"V\",\"measurand\":\"Voltage\",\"phase\":\"L2\"},{\"value\":\"0.000000\",\"unit\":\"V\",\"measurand\":\"Voltage\",\"phase\":\"L3\"},{\"value\":\"0.008000\",\"unit\":\"A\",\"measurand\":\"Current.Export\",\"phase\":\"L1\"},{\"value\":\"0.008000\",\"unit\":\"A\",\"measurand\":\"Current.Import\",\"phase\":\"L1\"},{\"value\":\"0.009000\",\"unit\":\"A\",\"measurand\":\"Current.Export\",\"phase\":\"L2\"},{\"value\":\"0.009000\",\"unit\":\"A\",\"measurand\":\"Current.Import\",\"phase\":\"L2\"},{\"value\":\"0.008000\",\"unit\":\"A\",\"measurand\":\"Current.Export\",\"phase\":\"L3\"},{\"value\":\"0.008000\",\"unit\":\"A\",\"measurand\":\"Current.Import\",\"phase\":\"L3\"},{\"value\":\"0\",\"unit\":\"W\",\"measurand\":\"Power.Offered\"},{\"value\":\"0\",\"unit\":\"W\",\"measurand\":\"Power.Active.Import\"}]}]}]")]
    [InlineData("[2,\"202505182007530000009C\",\"MeterValues\",{\"connectorId\":1,\"transactionId\":10,\"meterValue\":[{\"timestamp\":\"2025-05-18T20:05:11.000Z\",\"sampledValue\":[{\"value\":\"1402664\",\"context\":\"Transaction.Begin\",\"format\":\"Raw\",\"measurand\":\"Energy.Active.Import.Register\",\"phase\":\"L3\",\"location\":\"Outlet\",\"unit\":\"Wh\"}]}]}]")]
    [InlineData("[2,\"2025051820072700000099\",\"MeterValues\",{\"connectorId\":1,\"transactionId\":10,\"meterValue\":[{\"timestamp\":\"2025-05-18T20:07:53.000Z\",\"sampledValue\":[{\"value\":\"1402812\",\"unit\":\"Wh\",\"measurand\":\"Energy.Active.Import.Register\"},{\"value\":\"0.000000\",\"unit\":\"V\",\"measurand\":\"Voltage\",\"phase\":\"L1\"},{\"value\":\"0.000000\",\"unit\":\"V\",\"measurand\":\"Voltage\",\"phase\":\"L2\"},{\"value\":\"0.000000\",\"unit\":\"V\",\"measurand\":\"Voltage\",\"phase\":\"L3\"},{\"value\":\"0.009000\",\"unit\":\"A\",\"measurand\":\"Current.Export\",\"phase\":\"L1\"},{\"value\":\"0.009000\",\"unit\":\"A\",\"measurand\":\"Current.Import\",\"phase\":\"L1\"},{\"value\":\"0.009000\",\"unit\":\"A\",\"measurand\":\"Current.Export\",\"phase\":\"L2\"},{\"value\":\"0.009000\",\"unit\":\"A\",\"measurand\":\"Current.Import\",\"phase\":\"L2\"},{\"value\":\"0.009000\",\"unit\":\"A\",\"measurand\":\"Current.Export\",\"phase\":\"L3\"},{\"value\":\"0.009000\",\"unit\":\"A\",\"measurand\":\"Current.Import\",\"phase\":\"L3\"},{\"value\":\"0\",\"unit\":\"W\",\"measurand\":\"Power.Offered\"},{\"value\":\"0\",\"unit\":\"W\",\"measurand\":\"Power.Active.Import\"}]}]}]")]
    [InlineData("[2,\"202505182007550000009D\",\"MeterValues\",{\"connectorId\":1,\"transactionId\":10,\"meterValue\":[{\"timestamp\":\"2025-05-18T20:07:34.000Z\",\"sampledValue\":[{\"value\":\"1402812\",\"context\":\"Transaction.End\",\"format\":\"Raw\",\"measurand\":\"Energy.Active.Import.Register\",\"phase\":\"L3\",\"location\":\"Outlet\",\"unit\":\"Wh\"}]}]}]")]
    [InlineData("[2,\"202505182007330000009A\",\"MeterValues\",{\"connectorId\":1,\"transactionId\":10,\"meterValue\":[{\"timestamp\":\"2025-05-18T20:07:55.000Z\",\"sampledValue\":[{\"value\":\"1402812\",\"unit\":\"Wh\",\"measurand\":\"Energy.Active.Import.Register\"},{\"value\":\"0.000000\",\"unit\":\"V\",\"measurand\":\"Voltage\",\"phase\":\"L1\"},{\"value\":\"0.000000\",\"unit\":\"V\",\"measurand\":\"Voltage\",\"phase\":\"L2\"},{\"value\":\"0.000000\",\"unit\":\"V\",\"measurand\":\"Voltage\",\"phase\":\"L3\"},{\"value\":\"0.009000\",\"unit\":\"A\",\"measurand\":\"Current.Export\",\"phase\":\"L1\"},{\"value\":\"0.009000\",\"unit\":\"A\",\"measurand\":\"Current.Import\",\"phase\":\"L1\"},{\"value\":\"0.009000\",\"unit\":\"A\",\"measurand\":\"Current.Export\",\"phase\":\"L2\"},{\"value\":\"0.009000\",\"unit\":\"A\",\"measurand\":\"Current.Import\",\"phase\":\"L2\"},{\"value\":\"0.008000\",\"unit\":\"A\",\"measurand\":\"Current.Export\",\"phase\":\"L3\"},{\"value\":\"0.008000\",\"unit\":\"A\",\"measurand\":\"Current.Import\",\"phase\":\"L3\"},{\"value\":\"0\",\"unit\":\"W\",\"measurand\":\"Power.Offered\"},{\"value\":\"0\",\"unit\":\"W\",\"measurand\":\"Power.Active.Import\"}]}]}]")]
    public void CanDeserializeMeterValues(string json)
    {
        var doc = JsonDocument.Parse(json);
        var root = doc.RootElement;
        var payload = root.GetArrayLength() >= 4 ? root[3] : default;
        var service = Mock.Create<TeslaSolarCharger.Server.Services.OcppWebSocketConnectionHandlingService>();
        var response = service.HandleMeterValues("asdf", payload);
    }
}
