name: edgeRelease

on:
  pull_request:
    branches: [ master ]

jobs:
  TeslaSolarCharger:
    name: Building TeslaSolarCharger image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Determine Docker tag
      id: docker_tag
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          BRANCH_NAME="${{ github.head_ref }}"
        else
          BRANCH_NAME="${{ github.ref_name }}"
        fi
        
        if [[ "$BRANCH_NAME" == hotfix/* ]]; then
          echo "tag=hotfix" >> "$GITHUB_OUTPUT"
        else
          echo "tag=edge" >> "$GITHUB_OUTPUT"
        fi

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.x'

    - name: Install minver CLI
      run: dotnet tool install --tool-path ./minver minver-cli --version 4.3.0
          
    - name: Calculate version using minver CLI
      id: version
      run: |
          echo "version=$(./minver/minver --default-pre-release-identifiers edge --tag-prefix v)" >> "$GITHUB_ENV"
    
    - name: Run unit tests
      run: dotnet test TeslaSolarCharger.Tests
      
    - name: Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: DockerHub login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASS}}
        
    - name: Build and push TeslaSolarCharger
      uses: docker/build-push-action@v4
      with:
        build-args: MINVERVERSIONOVERRIDE=${{ env.version }}
        file: ./TeslaSolarCharger/Server/Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: pkuehnel/teslasolarcharger:${{ steps.docker_tag.outputs.tag }}

  SmaEnergymeterPlugin:
    name: Building SMAPlugin Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Determine Docker tag
      id: docker_tag
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          BRANCH_NAME="${{ github.head_ref }}"
        else
          BRANCH_NAME="${{ github.ref_name }}"
        fi
        
        if [[ "$BRANCH_NAME" == hotfix/* ]]; then
          echo "tag=hotfix" >> "$GITHUB_OUTPUT"
        else
          echo "tag=edge" >> "$GITHUB_OUTPUT"
        fi

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: DockerHub login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASS}}
        
    - name: Build and push SmaPlugin
      uses: docker/build-push-action@v4
      with:
        file: ./Plugins.SmaEnergymeter/Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: pkuehnel/teslasolarchargersmaplugin:${{ steps.docker_tag.outputs.tag }}

  SolarEdgePlugin:
    name: Building SolarEdgePlugin Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Determine Docker tag
      id: docker_tag
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          BRANCH_NAME="${{ github.head_ref }}"
        else
          BRANCH_NAME="${{ github.ref_name }}"
        fi
        
        if [[ "$BRANCH_NAME" == hotfix/* ]]; then
          echo "tag=hotfix" >> "$GITHUB_OUTPUT"
        else
          echo "tag=edge" >> "$GITHUB_OUTPUT"
        fi

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: DockerHub login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASS}}

    - name: Build and push SolarEdgePlugin
      uses: docker/build-push-action@v4
      with:
        file: ./Plugins.SolarEdge/Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: pkuehnel/teslasolarchargersolaredgeplugin:${{ steps.docker_tag.outputs.tag }}

  ModbusPlugin:
    name: Building ModbusPlugin Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Determine Docker tag
      id: docker_tag
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          BRANCH_NAME="${{ github.head_ref }}"
        else
          BRANCH_NAME="${{ github.ref_name }}"
        fi
        
        if [[ "$BRANCH_NAME" == hotfix/* ]]; then
          echo "tag=hotfix" >> "$GITHUB_OUTPUT"
        else
          echo "tag=edge" >> "$GITHUB_OUTPUT"
        fi

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: DockerHub login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASS}}

    - name: Build and push ModbusPlugin
      uses: docker/build-push-action@v4
      with:
        file: ./Plugins.Modbus/Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: pkuehnel/teslasolarchargermodbusplugin:${{ steps.docker_tag.outputs.tag }}

  SolaxPlugin:
    name: Building SolaxPlugin Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Determine Docker tag
      id: docker_tag
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          BRANCH_NAME="${{ github.head_ref }}"
        else
          BRANCH_NAME="${{ github.ref_name }}"
        fi
        
        if [[ "$BRANCH_NAME" == hotfix/* ]]; then
          echo "tag=hotfix" >> "$GITHUB_OUTPUT"
        else
          echo "tag=edge" >> "$GITHUB_OUTPUT"
        fi

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: DockerHub login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASS}}

    - name: Build and push SolaxPlugin
      uses: docker/build-push-action@v4
      with:
        file: ./Plugins.Solax/Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: pkuehnel/teslasolarchargersolaxplugin:${{ steps.docker_tag.outputs.tag }}